export * from "./types";
export * as authApi from "./auth";
export * as employeesApi from "./employees";
export * as tutorsApi from "./tutors";
export * as leadsApi from "./leads";
export * as studentsApi from "./students";
export * as couponsApi from "./coupons";
export * as notificationsApi from "./notifications";
export * as platformApi from "./platform";
export * as attendanceApi from "./attendance";
export * as dashboardApi from "./dashboard";
